#   Configure files for pyMP3duplicates.py 
#
#   true and false are lower case 
#   Configure files for pyMP3duplicates.py 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
#   <2023> (c) Kevin Scott

[INFO]
myVERSION = "2023.7"
myNAME = "pyWeatherApp"

[DATA]
directory = "data"
mainwWorkBook = "July2023"
target = "data//all*.xlsx"
