#   Configure files for pyDataBuild.py 
#
#   true and false are lower case 
#   location needs double \ i.e. c:\tmp\music - well, on windows any way. 
#
#   <2023> (c) Kevin Scott 

[INFO]
myVERSION = "2023.14"
myNAME = "pyWeatherApp"

[DATA]
directory = "data"
mainWB = "August2023"
mainDB = "September2023"
target = "data//2023//September//all*.xlsx"

[DB]
#  either "sqlite" OR "excel"
type = "sqlite"
