#   Configure files for pyWeatherApps.py
#
#   true and false are lower case
#
#   <2023> (c) Kevin Scott

[INFO]
myVERSION = "2023.26"
myNAME    = "pyWeatherApp"

[DATA]
data_dir = "data"
db_dir   = "db"
rec_dir  = "records"
month    = "December"
year     = "2023"
target   = "all*.xlsx"

[DB]
#  either "sqlite" OR "excel"
type = "sqlite"
