#   Configure files for pyWeatherApps.py
#
#   true and false are lower case
#
#   <2023 - 2024> (c) Kevin Scott

[INFO]
myVERSION = "2024.27"
myNAME    = "pyWeatherApp"

[DATA]
data_dir = "data"
xl_dir   = "xl"
db_dir   = "db"
rec_dir  = "records"
month    = "January"
year     = "2024"
target   = "all*.xlsx"

[DB]
#  either "sqlite" OR "excel"
type = "sqlite"
